/*
Copyright 2025 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

use std::ffi::{OsStr, OsString};
use std::fs::OpenOptions;
use std::io::Write;
use std::os::unix::ffi::OsStrExt;
use std::os::unix::fs::OpenOptionsExt;
use std::time::SystemTime;
use std::{
    collections::{HashMap, HashSet},
    sync::Arc,
};

mod path_alias;

use anyhow::Result;
use bytes::{Buf, BufMut, Bytes, BytesMut};
use memchr::{memchr2, memmem};
use parking_lot::Mutex;

use crate::error;
use crate::func::CommandOp;
use crate::io::{dump_int, dump_string, dump_systemtime, dump_usize, dump_vec_string};
use crate::strutil::{Pattern, basename, concat_dir, dirname, strip_ext, strip_ext_vec};
use crate::{
    build_sink::{
        BuildSink, DeferredRecipeId, NewInputsTiming, RecipeExpansion, RuleId, ShellEvaluation,
        SinkCommand, SinkEdge, SinkPool, SinkRule,
    },
    command::{
        Command, CommandEvaluator, expansion_can_reach_make, is_blank_recipe_line,
        references_new_inputs,
    },
    dep::{DepNode, NamedDepNode, is_buildable_target},
    eval::Evaluator,
    expr::Evaluable,
    flags::Flags,
    loc::Loc,
    strutil::{escape_shell, trim_left_space},
    symtab::{Interner, Symbol},
    timeutil::ScopedTimeReporter,
};
use path_alias::PhonyAliases;

/// The pool kati declares for itself, so that `--remote_num_jobs` can let ninja
/// run wide while the commands kati generated stay capped at `--jobs`.
const LOCAL_POOL: &[u8] = b"local_pool";

/// The synthetic target every `.PHONY` edge depends on when the manifest cannot
/// say `phony_output`. Nothing builds it, so ninja considers it dirty forever,
/// which is how a `.PHONY` target gets Make's always-run behaviour through a
/// file format that only knows about files.
///
/// This exists for the manifest and nowhere else, which is why it is invented
/// here rather than pushed through [`BuildSink`].
const ALWAYS_BUILD: &[u8] = b"_kati_always_build_";

/// Where a script too long for an argument list is written.
///
/// Also a ninja expression, and also the writer's alone: it is one file per
/// edge because `$out` is, and it exists because a manifest can only pass a
/// command as a string. A sink holding the script in memory needs no file, so
/// [`SinkCommand::ResponseFile`] says only that the script is too long to be an
/// argument, and leaves where it lands to whoever has to land it.
const RESPONSE_FILE: &str = "$out.rsp";

fn find_command_line_flag(cmd: &[u8], name: &[u8]) -> Option<usize> {
    match memmem::find(cmd, name) {
        Some(0) => None,
        found => found,
    }
}

fn find_command_line_flag_with_arg(cmd: &[u8], name: &[u8]) -> Option<Vec<u8>> {
    let idx = find_command_line_flag(cmd, name)?;

    let mut val = trim_left_space(&cmd[idx + name.len()..]);
    while let Some(idx) = memmem::find(val, name) {
        val = trim_left_space(&val[idx + name.len()..]);
    }

    let Some(idx) = memchr2(b' ', b'\t', val) else {
        return Some(val.to_vec());
    };
    Some(val[..idx].to_vec())
}

fn get_depfile_from_command_impl(cmd: &mut BytesMut) -> Result<Option<Vec<u8>>> {
    if (find_command_line_flag(cmd, b" -MD").is_none()
        && find_command_line_flag(cmd, b" -MMD").is_none())
        || find_command_line_flag(cmd, b" -c").is_none()
    {
        return Ok(None);
    }

    if let Some(mf) = find_command_line_flag_with_arg(cmd, b" -MF") {
        return Ok(Some(mf));
    }

    let Some(o) = find_command_line_flag_with_arg(cmd, b" -o") else {
        error!(
            "Cannot find the depfile in {}",
            String::from_utf8_lossy(cmd.as_ref())
        );
    };

    let mut o = strip_ext_vec(o);
    o.extend_from_slice(b".d");
    Ok(Some(o))
}

fn get_depfile_from_command(cmd: &mut BytesMut) -> Result<Option<Bytes>> {
    assert!(!cmd.is_empty());
    let Some(mut out) = get_depfile_from_command_impl(cmd)? else {
        return Ok(None);
    };

    // A hack for Android - llvm-rs-cc seems not to emit a dep file.
    if memmem::find(cmd, b"bin/llvm-rs-cc ").is_some() {
        return Ok(None);
    }

    // TODO: A hack for Makefiles generated by automake.

    // A hack for Android to get .P files instead of .d.
    let mut p = strip_ext_vec(out.clone());
    p.extend_from_slice(b".P");
    if memmem::find(cmd, &p).is_some() {
        let mut rm_f = b"; rm -f ".to_vec();
        rm_f.extend_from_slice(&out);
        let Some(found) = memmem::find(cmd, &rm_f) else {
            error!(
                "Cannot find remove of .d file: {}",
                String::from_utf8_lossy(cmd.as_ref())
            );
        };
        let after = cmd[found + rm_f.len()..].to_vec();
        cmd.truncate(found);
        cmd.extend_from_slice(&after);
        return Ok(Some(Bytes::from(out)));
    }

    // A hack for Android. For .s files, GCC does not use C
    // preprocessor, so it ignores -MF flag.
    let mut a_s = b"/".to_vec();
    a_s.extend_from_slice(strip_ext(basename(&out)));
    a_s.extend_from_slice(b".s");
    if memmem::find(cmd, &a_s).is_some() {
        return Ok(None);
    }

    cmd.extend_from_slice(b"&& cp ");
    cmd.extend_from_slice(&out);
    cmd.put_u8(b' ');
    cmd.extend_from_slice(&out);
    cmd.extend_from_slice(b".tmp ");
    out.extend_from_slice(b".tmp");
    Ok(Some(Bytes::from(out)))
}

struct NinjaNode {
    node: Arc<Mutex<DepNode>>,
    commands: Vec<Command>,
    rule_id: Option<RuleId>,
    deferred_new_inputs: bool,
    deferred_new_inputs_filter_out: Vec<Bytes>,
    /// The recipe was left unexpanded for the sink to expand at launch, so
    /// `commands` is empty because nothing has read it yet rather than because
    /// the node has none.
    deferred_recipe: bool,
}

/// One recipe left unexpanded, and everything the expansion will need that is
/// not on the node itself.
struct DeferredRecipe {
    node: Arc<Mutex<DepNode>>,
    /// What to print while the command runs when the recipe supplies no
    /// description of its own and the node's own name is not addressable.
    /// Decided while the graph is constructed, because it is a fact about the
    /// graph rather than about the recipe.
    description_fallback: Option<Bytes>,
    shell: Bytes,
}

/// The recipes a [`RecipeExpansion::Launch`] sink asked to expand for itself.
///
/// Held by the destination for as long as it may still run one of them. The
/// evaluator that produced them has to be held with it: a recipe is expanded
/// in the session that read the Makefile, against the variables that session
/// holds, which is what makes an expansion at launch the same expansion GNU
/// Make would have done there.
pub struct DeferredRecipes {
    recipes: Vec<DeferredRecipe>,
}

/// One expanded recipe: what a [`SinkRule`] would have carried, had the text
/// existed when the rule was declared.
pub struct ExpandedRecipe {
    /// The shell to run the script under, unescaped.
    pub shell: Bytes,
    /// The flags that make the shell take the script as an argument.
    pub shell_flags: Bytes,
    /// The assembled shell script.
    pub script: Bytes,
    /// What to print while the command runs, when something chose.
    pub description: Option<Bytes>,
    /// A nonzero status is an error Make was told to ignore.
    pub ignore_errors: bool,
}

impl DeferredRecipes {
    /// Whether anything was deferred at all.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.recipes.is_empty()
    }

    /// Expand one recipe into the command text that should run now.
    ///
    /// This is GNU Make's `new_job`: the whole recipe is expanded in one go,
    /// immediately before the first line of it runs, so a line cannot observe
    /// what an earlier line of the same recipe did, while it observes
    /// everything every earlier recipe did.
    ///
    /// # Errors
    ///
    /// Whatever expanding the recipe rejects — an `$(error)`, an undefined
    /// function, a `$(shell)` that could not be started. GNU Make reports
    /// these only for a recipe it was about to run, and so does this.
    pub fn expand(
        &self,
        ev: &mut Evaluator,
        id: DeferredRecipeId,
    ) -> Result<Option<ExpandedRecipe>> {
        let Some(recipe) = self.recipes.get(id) else {
            return Ok(None);
        };
        // Every recipe that reached this one ran and was waited for, which in
        // GNU Make is what ages the directory cache. Expanding a recipe is
        // therefore the one place in a build where a `$(wildcard)` has to look
        // again, and the reason it sees what the recipes before it made.
        ev.session.note_command_ran();
        let mut ce = CommandEvaluator::new(
            ev,
            // The prerequisites are built and the timestamps on disk are the
            // ones GNU Make compares, so `$?` is answered here rather than
            // deferred to a scheduler that has already done its part.
            NewInputsTiming::Launch,
            ShellEvaluation::Expansion,
        )?;
        ce.ev.avoid_io = true;
        let expanded = Self::expand_with(&mut ce, recipe);
        ce.ev.avoid_io = false;
        ce.ev.new_inputs_timing = NewInputsTiming::RecipeShell;
        ce.ev.shell_evaluation = ShellEvaluation::RecipeShell;
        ce.ev.deferred_new_inputs_filter_out.clear();
        expanded.map(Some)
    }

    fn expand_with(
        ce: &mut CommandEvaluator<'_>,
        recipe: &DeferredRecipe,
    ) -> Result<ExpandedRecipe> {
        let (loc, output) = {
            let node = recipe.node.lock();
            (node.loc.clone(), node.output.as_bytes(&ce.ev.session))
        };
        let _frame = ce.ev.enter(
            crate::eval::FrameType::Ninja,
            output,
            loc.unwrap_or_default(),
        );
        let commands = ce.eval(&recipe.node)?;
        // The classification that decided this recipe could be deferred is
        // made before anything is expanded, so it is checked here against what
        // the expansion actually did. A recursive invocation reaching this
        // point would be a nested Make process rather than a composed child
        // graph, which is the one thing the compiler must never hand its
        // executor.
        if commands
            .iter()
            .any(|command| !command.recursive_make.is_empty() || command.uncomposable_recursion)
        {
            anyhow::bail!(
                "recipe for {} reached a recursive Make invocation the compiler could not see before expanding it",
                String::from_utf8_lossy(&recipe.node.lock().output.as_bytes(&ce.ev.session))
            );
        }
        let recipe_output = recipe.node.lock().recipe_output.as_bytes(&ce.ev.session);
        let mut description = None;
        let mut script = BytesMut::new();
        // A recipe every line of which expanded to nothing has no line to read
        // flags from, and still has to reach the shell as the empty script it
        // is: GNU Make runs nothing and counts the target as remade.
        let shell_flags = if commands.is_empty() {
            ce.ev.get_shell_flag(false)?
        } else {
            NinjaGenerator::script_shell_flags(&ce.ev.session.flags, &commands)
        };
        let ignore_errors = NinjaGenerator::gen_shell_script(
            &ce.ev.session.flags,
            &recipe_output,
            &commands,
            &shell_flags,
            &mut script,
            &mut description,
        );
        if description.is_none() {
            description.clone_from(&recipe.description_fallback);
        }
        Ok(ExpandedRecipe {
            shell: recipe.shell.clone(),
            shell_flags,
            script: script.freeze(),
            description,
            ignore_errors,
        })
    }
}

struct NinjaGenerator<'a> {
    ce: CommandEvaluator<'a>,
    done: HashSet<Symbol>,
    rule_id: RuleId,
    shell: Bytes,
    used_envs: HashMap<Symbol, OsString>,
    nodes: Vec<NinjaNode>,
    phony_aliases: PhonyAliases,
    recipe_expansion: RecipeExpansion,
    deferred_recipes: Vec<DeferredRecipe>,
}

impl<'a> NinjaGenerator<'a> {
    fn new(ce: CommandEvaluator<'a>, recipe_expansion: RecipeExpansion) -> Result<Self> {
        // Unescaped: whether these need escaping is a question about the
        // destination, so the answer belongs to whatever is on the far side of
        // the sink.
        let shell = ce.ev.get_shell()?;
        ce.ev.avoid_io = true;
        Ok(Self {
            ce,
            done: HashSet::new(),
            rule_id: 0,
            shell,
            used_envs: HashMap::new(),
            nodes: Vec::new(),
            phony_aliases: PhonyAliases::default(),
            recipe_expansion,
            deferred_recipes: Vec::new(),
        })
    }

    /// Whether this node's recipe can be left for the destination to expand
    /// when it runs it.
    ///
    /// Everything refused here is refused because the compiler itself has to
    /// read the recipe's text before the graph is complete: a recursive
    /// `$(MAKE)` line becomes a child graph, an automatic or declared depfile
    /// rewrites the script and names a file on the rule, a grouped
    /// double-colon action and a `$?` are values the scheduler binds against
    /// an edge that has to declare them. The recipe as written is what decides
    /// — the same classification GNU Make makes before it expands anything.
    fn defers_recipe(&self, node: &DepNode) -> bool {
        if self.recipe_expansion != RecipeExpansion::Launch || node.cmds.is_empty() {
            return false;
        }
        // A recipe of nothing but whitespace is a target remade by doing
        // nothing, and the graph says that with an edge that runs nothing.
        // Deferring it would mint a rule for a command that will never exist.
        if node.cmds.iter().all(|cmd| is_blank_recipe_line(cmd)) {
            return false;
        }
        if node.depfile_var.is_some()
            || self.ce.ev.session.flags.detect_depfiles
            || node.grouped_double_action.is_some()
            || node.grouped_double_join
        {
            return false;
        }
        let rule_vars = node.rule_vars.clone();
        node.cmds.iter().all(|cmd| {
            let mut seen = HashSet::new();
            !expansion_can_reach_make(cmd, self.ce.ev, rule_vars.as_deref(), &mut seen)
                && !references_new_inputs(cmd, &self.ce.ev.session)
        })
    }

    fn generate(
        &mut self,
        nodes: &Vec<NamedDepNode>,
        orig_args: &[u8],
        start_time: SystemTime,
    ) -> Result<()> {
        let _ = std::fs::remove_file(self.get_stamp_temp_filename());
        self.populate_ninja_nodes(nodes)?;
        self.generate_ninja()?;
        self.generate_shell()?;
        self.generate_stamp(orig_args, start_time)?;
        Ok(())
    }

    fn get_stamp_temp_filename(&self) -> OsString {
        ninja_file(&self.ce.ev.session.flags, ".kati_stamp", ".tmp")
    }

    fn populate_ninja_nodes(&mut self, nodes: &Vec<NamedDepNode>) -> Result<()> {
        let _tr = ScopedTimeReporter::new(&self.ce.ev.session, "ninja gen (eval)");
        for (_symbol, depnode) in nodes {
            self.populate_ninja_node(depnode)?;
        }
        let mut occupied = self.done.clone();
        let mut phonies = Vec::new();
        for generated in &self.nodes {
            let node = generated.node.lock();
            occupied.extend(node.implicit_outputs.iter().copied());
            if node.is_phony {
                phonies.push(node.output);
            }
        }
        self.phony_aliases
            .prepare(&mut self.ce.ev.session.symtab, &occupied, &phonies);
        Ok(())
    }

    fn populate_ninja_node(&mut self, node: &Arc<Mutex<DepNode>>) -> Result<()> {
        let output = node.lock().output;
        if self.done.contains(&output) {
            return Ok(());
        }
        self.done.insert(output);
        let loc;
        let has_rule;
        let is_phony;
        {
            let node = node.lock();
            loc = node.loc.clone();
            has_rule = node.has_rule;
            is_phony = node.is_phony;
        }
        let output_str = output.as_bytes(&self.ce.ev.session);
        let _frame = self.ce.ev.enter(
            crate::eval::FrameType::Ninja,
            output_str.clone(),
            loc.unwrap_or_default(),
        );

        // A hack to exclude out phony target in Android. If this exists,
        // "ninja -t clean" tries to remove this directory and fails.
        if self.ce.ev.session.flags.detect_android_echo && output_str.as_ref() == b"out" {
            return Ok(());
        }

        // This node is a leaf node
        if !has_rule && !is_phony {
            return Ok(());
        }

        // A deferred recipe is not read here at all. That is the whole of the
        // difference: an up-to-date target's `$(shell)` never runs, its
        // `$(error)` never fires, and its `$(wildcard)` is answered against
        // the files that exist when the command is about to run rather than
        // against the ones that existed before the build started.
        let deferred_recipe = self.defers_recipe(&node.lock());
        let commands = if deferred_recipe {
            Vec::new()
        } else {
            self.ce.eval(node)?
        };
        let deferred_new_inputs = self.ce.ev.new_inputs_timing
            == NewInputsTiming::SchedulerBoundary
            && *self.ce.found_new_inputs.lock();
        let deferred_new_inputs_filter_out =
            std::mem::take(&mut self.ce.ev.deferred_new_inputs_filter_out);
        let rule_id = if commands.is_empty() && !deferred_recipe {
            None
        } else {
            let id = self.rule_id;
            self.rule_id += 1;
            Some(id)
        };

        self.nodes.push(NinjaNode {
            node: node.clone(),
            commands,
            rule_id,
            deferred_new_inputs,
            deferred_new_inputs_filter_out,
            deferred_recipe,
        });

        let deps = node.lock().deps.clone();
        for (_symbol, depnode) in deps {
            self.populate_ninja_node(&depnode)?;
        }

        let order_onlys = node.lock().order_onlys.clone();
        for (_symbol, depnode) in order_onlys {
            self.populate_ninja_node(&depnode)?;
        }

        let validations = node.lock().validations.clone();
        for (_symbol, depnode) in validations {
            self.populate_ninja_node(&depnode)?;
        }

        Ok(())
    }

    /// Turn one Make recipe line into the command line a shell should receive.
    ///
    /// Make's own syntax is already gone by the time this runs — the evaluator
    /// has expanded the variables, so a `$` still here is a `$$` the Makefile
    /// wrote and therefore a `$` the shell is meant to see. What is left to
    /// remove is shell-level: comments, the backslash-newline continuations
    /// Make allows inside a recipe, and trailing separators.
    ///
    /// Nothing here is about Ninja. The result is the command, and whoever
    /// writes it into a file escapes it for that file.
    fn translate_command(inp: Bytes) -> Bytes {
        let mut cmd_buf = BytesMut::new();
        let mut prev_backslash = false;
        // Set space as an initial value so the leading comment will be
        // stripped out.
        let mut prev_char = b' ';
        let mut quote = None;
        let mut inp = inp;
        while let Some(&c) = inp.first() {
            match c {
                b'#' => {
                    if quote.is_none() && prev_char.is_ascii_whitespace() {
                        while inp.len() > 1 && inp[0] != b'\n' {
                            inp.advance(1);
                        }
                        // The comment ran to the end of its line and took the
                        // newline with it, and it took the backslash that
                        // continued the line into it too — a backslash inside a
                        // comment is comment text. What follows therefore reads
                        // as the start of a line: a `#` there opens another
                        // comment rather than being a word of this one.
                        prev_backslash = false;
                        prev_char = b'\n';
                        inp.advance(1);
                        continue;
                    }
                    cmd_buf.put_u8(c);
                }
                b'\'' | b'"' | b'`' => {
                    if let Some(q) = quote {
                        if q == c {
                            quote = None;
                        }
                    } else if !prev_backslash {
                        quote = Some(c);
                    }
                    cmd_buf.put_u8(c);
                }
                b'\n' => {
                    if prev_backslash {
                        cmd_buf.truncate(cmd_buf.len() - 1);
                    } else {
                        cmd_buf.put_u8(b' ');
                    }
                }
                _ => cmd_buf.put_u8(c),
            }

            if c == b'\\' {
                prev_backslash = !prev_backslash;
            } else {
                prev_backslash = false;
            }

            prev_char = c;
            inp.advance(1);
        }

        if prev_backslash {
            cmd_buf.truncate(cmd_buf.len() - 1);
        }

        while !cmd_buf.is_empty() {
            let c = *cmd_buf.last().unwrap();
            if !c.is_ascii_whitespace() && c != b';' {
                break;
            }
            cmd_buf.truncate(cmd_buf.len() - 1);
        }

        cmd_buf.freeze()
    }

    fn is_output_mkdir(name: &Bytes, cmd: &Bytes) -> bool {
        let Some(cmd) = cmd.strip_prefix(b"mkdir -p ") else {
            return false;
        };

        let cmd = match cmd.strip_suffix(b"/") {
            Some(c) => c,
            None => cmd,
        };

        cmd == dirname(name)
    }

    /// The text a lone `echo` was going to print, which is a better thing to
    /// show while the command runs than the command itself.
    ///
    /// This is a literal string, not a format: it is what the Makefile said,
    /// with the shell quoting taken off.
    fn get_description_from_command(cmd: &Bytes) -> Option<Bytes> {
        let cmd = cmd.strip_prefix(b"echo ")?;

        let mut prev_backslash = false;
        let mut quote = None;
        let mut out_buf = BytesMut::new();

        // Strip outer quotes, and fail if it is not a single echo command
        for c in cmd {
            let c = *c;
            if prev_backslash {
                prev_backslash = false;
                out_buf.put_u8(c);
            } else if c == b'\\' {
                prev_backslash = true;
                out_buf.put_u8(c);
            } else if let Some(q) = quote {
                if c == q {
                    quote = None;
                } else {
                    out_buf.put_u8(c);
                }
            } else {
                match c {
                    b'\'' | b'"' | b'`' => quote = Some(c),
                    b'<' | b'>' | b'&' | b'|' | b';' => return None,
                    _ => out_buf.put_u8(c),
                }
            }
        }

        Some(out_buf.freeze())
    }

    /// The flags the whole fused script runs under.
    ///
    /// GNU Make invokes every recipe line separately, so each line's flags are
    /// its own. A manifest has one invocation per recipe, so the line that
    /// cannot bend governs: a line with no `-` prefix needs whatever `.POSIX:`
    /// gave it, and the prefixed lines take the `-e` off again themselves —
    /// which is the `set +e` in [`Self::gen_shell_script`]. When every line is
    /// prefixed there is nothing to accommodate and the relaxed flags govern.
    ///
    /// `.ONESHELL` is the case where one invocation is not an approximation,
    /// and GNU Make reads the first line's prefix for it.
    fn script_shell_flags(flags: &Flags, commands: &[Command]) -> Bytes {
        let Some(first) = commands.first() else {
            return Bytes::new();
        };
        if flags.one_shell {
            return first.shell_flag.clone();
        }
        commands
            .iter()
            .find(|c| !c.dash_prefixed)
            .unwrap_or(first)
            .shell_flag
            .clone()
    }

    /// Assemble the recipe into one shell script, and say what to print while
    /// it runs if the recipe itself said so.
    ///
    /// `description` is left `None` when the Makefile did not say. Each sink
    /// can then narrate an inline recipe with the expanded script itself,
    /// without making this front end choose a destination-specific format.
    ///
    /// Returns whether the script's own status can be read as an ignored
    /// error, which is [`SinkRule::ignore_errors`].
    fn gen_shell_script(
        flags: &Flags,
        name: &Bytes,
        commands: &[Command],
        script_flags: &[u8],
        cmd_buf: &mut BytesMut,
        description: &mut Option<Bytes>,
    ) -> bool {
        // A nonzero status is certainly an ignored failure only when every line
        // ignores errors: otherwise it may be the `&&` chain stopping at a line
        // whose failure counts. Read over every command rather than the ones
        // that survive the loop, so dropping one can only make this stricter.
        let wholly_ignored = !commands.is_empty() && commands.iter().all(|c| c.ignore_error);
        // Ignored lines are chained rather than conjoined, so the next line runs
        // whatever the last one left and the last line's status is the script's.
        let separator: &[u8] = match (flags.one_shell, wholly_ignored) {
            (true, _) => b"\n",
            (false, true) => b" ; ",
            (false, false) => b" && ",
        };
        let mut command_count = commands.len();
        for c in commands {
            let inp = c.cmd.slice_ref(c.cmd.trim_ascii_start());

            // Under `.ONESHELL` the recipe is one script: no subshell to
            // confine a `cd`, and the lines are separated rather than chained,
            // so a failing one does not stop the rest.
            let needs_subshell =
                !flags.one_shell && (command_count > 1 || c.ignore_error) && !c.force_no_subshell;

            let mut translated = Self::translate_command(inp);
            let echoed = (flags.detect_android_echo && description.is_none() && !c.echo)
                .then(|| Self::get_description_from_command(&translated))
                .flatten();
            if let Some(echoed) = echoed {
                *description = Some(echoed);
                translated.clear();
            } else if Self::is_output_mkdir(name, &translated) && !c.echo && cmd_buf.is_empty() {
                translated.clear();
            }
            if translated.is_empty() {
                command_count -= 1;
                continue;
            }

            // An ignored line the script cannot speak for has to lose its
            // status here, because a later line needs the one channel out. The
            // subshell goes inside the group, so `exit` reaches the `true`
            // instead of leaving before it, and the group keeps the `&&` chain
            // able to stop at a line whose failure counts.
            let mute = c.ignore_error && !flags.one_shell && !wholly_ignored;
            // The script runs under flags this line did not ask for, which
            // under `.POSIX:` means it asked for a shell without `-e`. Taking
            // `-e` off again inside the line's own subshell gives the line the
            // shell GNU Make would have given it and leaves the rest of the
            // script strict. Only a `-` prefix can ask for this, and a
            // prefixed line always has a subshell to put it in: the prefix
            // makes `ignore_error` true, which `force_no_subshell` never is.
            let relax = !flags.one_shell && c.shell_flag != script_flags;

            let mut fragment = BytesMut::new();
            if mute {
                fragment.put_slice(b"{ ");
            }
            if needs_subshell {
                fragment.put_u8(b'(');
            }
            if relax {
                fragment.put_slice(b"set +e ; ");
            }
            fragment.put_slice(&translated);
            if needs_subshell {
                fragment.put_slice(b" )");
            }
            if mute {
                fragment.put_slice(b" ; true ; }");
            }

            if !cmd_buf.is_empty() {
                cmd_buf.put_slice(separator);
            }
            cmd_buf.put_slice(&fragment);
        }
        // A script with nothing left in it has no status to read, and a whole
        // recipe can be absorbed: a lone `mkdir -p` of the output's directory.
        wholly_ignored && !cmd_buf.is_empty()
    }

    fn get_depfile(&mut self, node: &DepNode, cmd_buf: &mut BytesMut) -> Result<Option<Bytes>> {
        if let Some(depfile_var) = node.depfile_var.clone() {
            let depfile = depfile_var.read().eval_to_buf(self.ce.ev)?;
            return Ok(Some(depfile));
        }
        if !self.ce.ev.session.flags.detect_depfiles {
            return Ok(None);
        }

        cmd_buf.put_u8(b' ');
        let result = get_depfile_from_command(cmd_buf);
        cmd_buf.truncate(cmd_buf.len() - 1);
        result
    }

    /// Which pool this node's edge belongs in.
    ///
    /// `.KATI_NINJA_POOL` wins, and names `none` to opt out of the fallbacks.
    /// Failing that `--default_pool` applies to anything that runs a command,
    /// and failing that `--remote_num_jobs` puts every edge in kati's own pool
    /// so that a wide ninja does not run wide locally.
    fn resolve_pool(&mut self, node: &DepNode, has_rule: bool) -> Result<Option<Bytes>> {
        let named = if let Some(ninja_pool_var) = &node.ninja_pool_var {
            Some(ninja_pool_var.read().eval_to_buf(self.ce.ev)?)
        } else {
            None
        };
        if let Some(named) = named.filter(|pool| !pool.is_empty()) {
            return Ok(if named.as_ref() == b"none" {
                None
            } else {
                Some(named)
            });
        }
        let flags = &self.ce.ev.session.flags;
        if !flags.default_pool.is_empty() && has_rule {
            return Ok(Some(Bytes::copy_from_slice(flags.default_pool.as_bytes())));
        }
        if flags.remote_num_jobs > 0 {
            return Ok(Some(Bytes::from_static(LOCAL_POOL)));
        }
        Ok(None)
    }

    /// Hand one dependency node to the sink as at most one rule and one edge.
    ///
    /// Returns the node's output if it is the default target, which is decided
    /// here rather than in the sink because it is a fact about the Makefile.
    fn sink_node(&mut self, nn: &NinjaNode, sink: &mut dyn BuildSink) -> Result<Option<Symbol>> {
        let node = nn.node.lock();
        if !is_buildable_target(&self.ce.ev.session, &node.output) {
            return Ok(None);
        }

        let rule_id = if nn.deferred_recipe {
            let id = nn.rule_id.expect("a deferred recipe mints a rule");
            let recipe_output_str = node.recipe_output.as_bytes(&self.ce.ev.session);
            let description_fallback = (self.phony_aliases.resolve(node.output) != node.output)
                .then(|| recipe_output_str.clone());
            let deferred = self.deferred_recipes.len();
            self.deferred_recipes.push(DeferredRecipe {
                node: nn.node.clone(),
                description_fallback,
                shell: self.shell.clone(),
            });
            sink.declare_rule(
                &self.ce.ev.session,
                &SinkRule {
                    id,
                    shell: &self.shell,
                    // Absent rather than empty: the recipe these come from has
                    // not been read yet.
                    shell_flags: b"",
                    command: SinkCommand::Inline(b""),
                    deferred_recipe: Some(deferred),
                    subninjas: &[],
                    contains_recursive: false,
                    residual_command: None,
                    residual_ignore_errors: false,
                    description: None,
                    depfile: None,
                    restat: node.is_restat,
                    ignore_errors: false,
                    sandbox_disabled: self.ce.ev.session.flags.emit_sandbox_disabled,
                    loc: node.loc.as_ref(),
                },
            )?;
            Some(id)
        } else if nn.commands.is_empty() {
            None
        } else {
            let id = nn.rule_id.unwrap();
            let mut description = None;
            let mut cmd_buf = BytesMut::new();
            let recipe_output_str = node.recipe_output.as_bytes(&self.ce.ev.session);
            let script_flags = Self::script_shell_flags(&self.ce.ev.session.flags, &nn.commands);
            let ignore_errors = Self::gen_shell_script(
                &self.ce.ev.session.flags,
                &recipe_output_str,
                &nn.commands,
                &script_flags,
                &mut cmd_buf,
                &mut description,
            );
            if description.is_none()
                && (self.phony_aliases.resolve(node.output) != node.output
                    || node.grouped_double_action.is_some())
            {
                description = Some(recipe_output_str.clone());
            }
            // Extracting the depfile can rewrite the command, so it has to
            // happen before the command is measured or handed over.
            let depfile = self.get_depfile(&node, &mut cmd_buf)?;

            // It seems Linux is OK with ~130kB and Mac's limit is ~250kB.
            // TODO: Find this number automatically.
            let too_long_for_argv = cmd_buf.len() > 100 * 1000;
            let script = cmd_buf.freeze();
            let contains_recursive = nn
                .commands
                .iter()
                .any(|command| !command.recursive_make.is_empty());
            // Splitting is all-or-nothing. A sink must never receive a
            // plausible-looking prefix while another recursive line remains
            // hidden in the discarded executor script. A multi-line
            // `.ONESHELL` recipe shares shell state across lines, and more
            // than one MAKE reference on a line does not identify one static
            // child compilation. A line GNU Make classified recursive whose
            // invocation cannot be lifted out is the third way that happens,
            // and the one that used to pass unseen: it carries no
            // `recursive_make`, so it would have been read as ordinary
            // residual work and left to start a nested Make beside the child
            // graphs its siblings became.
            let composable_subninjas = contains_recursive
                && (!self.ce.ev.session.flags.one_shell || nn.commands.len() == 1)
                && nn
                    .commands
                    .iter()
                    .all(|command| !command.uncomposable_recursion)
                && nn
                    .commands
                    .iter()
                    .filter(|command| !command.recursive_make.is_empty())
                    .all(|command| command.recursive_make.len() == 1);
            let subninja_storage = if composable_subninjas {
                nn.commands
                    .iter()
                    .filter_map(|command| {
                        let [make] = command.recursive_make.as_slice() else {
                            return None;
                        };
                        Some((
                            Self::translate_command(
                                command.cmd.slice_ref(command.cmd.trim_ascii_start()),
                            ),
                            make.clone(),
                        ))
                    })
                    .collect::<Vec<_>>()
            } else {
                Vec::new()
            };
            let subninjas = subninja_storage
                .iter()
                .map(|(command, make)| crate::build_sink::SinkSubninja { command, make })
                .collect::<Vec<_>>();
            let residual_commands = if composable_subninjas {
                nn.commands
                    .iter()
                    .filter(|command| command.recursive_make.is_empty())
                    .cloned()
                    .collect::<Vec<_>>()
            } else {
                Vec::new()
            };
            let mut residual_buf = BytesMut::new();
            let mut residual_description = None;
            // The residual is a subset of the same recipe and reaches the same
            // shell, so it is assembled against the flags that shell has.
            let residual_ignore_errors = Self::gen_shell_script(
                &self.ce.ev.session.flags,
                &recipe_output_str,
                &residual_commands,
                &script_flags,
                &mut residual_buf,
                &mut residual_description,
            );
            // Automatic depfile detection appends the copy to kati's manifest
            // command. The direct graph runs the residual command instead, so
            // it needs the identical transformation and must name the same
            // discovered file.
            if composable_subninjas
                && !residual_buf.is_empty()
                && node.depfile_var.is_none()
                && self.ce.ev.session.flags.detect_depfiles
            {
                let residual_depfile = get_depfile_from_command(&mut residual_buf)?;
                if residual_depfile != depfile {
                    return Err(anyhow::anyhow!(
                        "recursive recipe residual selected a different depfile"
                    ));
                }
            }
            let residual_too_long = residual_buf.len() > 100 * 1000;
            let residual_script = residual_buf.freeze();
            sink.declare_rule(
                &self.ce.ev.session,
                &SinkRule {
                    id,
                    shell: &self.shell,
                    shell_flags: &script_flags,
                    command: if too_long_for_argv {
                        SinkCommand::ResponseFile(&script)
                    } else {
                        SinkCommand::Inline(&script)
                    },
                    deferred_recipe: None,
                    subninjas: &subninjas,
                    contains_recursive,
                    residual_command: (!residual_script.is_empty()).then_some(
                        if residual_too_long {
                            SinkCommand::ResponseFile(&residual_script)
                        } else {
                            SinkCommand::Inline(&residual_script)
                        },
                    ),
                    residual_ignore_errors,
                    description: description.as_deref(),
                    depfile: depfile.as_deref(),
                    restat: node.is_restat,
                    ignore_errors,
                    sandbox_disabled: self.ce.ev.session.flags.emit_sandbox_disabled,
                    loc: node.loc.as_ref(),
                },
            )?;
            Some(id)
        };

        let pool = self.resolve_pool(&node, rule_id.is_some())?;
        let tags = if let Some(tags_var) = &node.tags_var {
            let tags = tags_var.read().eval_to_buf(self.ce.ev)?;
            if tags.is_empty() { None } else { Some(tags) }
        } else {
            None
        };

        // The sink is given the names, not the nodes behind them: an edge
        // refers to its inputs, it does not own them.
        let symbols = |deps: &[NamedDepNode]| {
            deps.iter()
                .map(|(symbol, _)| self.phony_aliases.resolve(*symbol))
                .collect::<Vec<_>>()
        };
        let named = |names: &[Symbol]| {
            names
                .iter()
                .map(|name| self.phony_aliases.resolve(*name))
                .collect::<Vec<_>>()
        };
        let inputs = symbols(&node.deps);
        let order_only_inputs = symbols(&node.order_onlys);
        let validations = symbols(&node.validations);
        let implicit_outputs = named(&node.implicit_outputs);
        let output = self.phony_aliases.resolve(node.output);
        let delete_on_error_outputs = named(&node.delete_on_error_outputs);
        let peer_outputs = named(&node.peer_outputs);
        let deferred_freshness_outputs = if let Some(action) = &node.grouped_double_action {
            named(&action.members)
        } else if nn.deferred_new_inputs {
            vec![self.phony_aliases.resolve(node.recipe_output)]
        } else {
            Vec::new()
        };
        let deferred_always_new_inputs = if let Some(action) = &node.grouped_double_action {
            named(&action.phony_inputs)
        } else if nn.deferred_new_inputs {
            node.deps
                .iter()
                .filter(|(_, dependency)| dependency.lock().is_phony)
                .map(|(input, _)| self.phony_aliases.resolve(*input))
                .collect::<Vec<_>>()
        } else {
            Vec::new()
        };
        let visible_inputs = node.actual_inputs.iter().copied().collect::<HashSet<_>>();
        let filter_out = nn
            .deferred_new_inputs_filter_out
            .iter()
            .cloned()
            .map(Pattern::new)
            .collect::<Vec<_>>();
        let deferred_excluded_new_inputs = if nn.deferred_new_inputs {
            node.deps
                .iter()
                .filter_map(|(input, _)| {
                    let name = input.as_bytes(&self.ce.ev.session);
                    (!visible_inputs.contains(input)
                        || filter_out.iter().any(|pattern| pattern.matches(&name)))
                    .then(|| self.phony_aliases.resolve(*input))
                })
                .collect::<Vec<_>>()
        } else {
            Vec::new()
        };

        sink.declare_edge(
            &self.ce.ev.session,
            &SinkEdge {
                rule: rule_id,
                output,
                implicit_outputs: &implicit_outputs,
                inputs: &inputs,
                order_only_inputs: &order_only_inputs,
                validations: &validations,
                always_dirty: node.is_phony || node.unconditional_double_colon,
                deferred_freshness_outputs: &deferred_freshness_outputs,
                // A completion join owns no members of its own, so it has no
                // freshness of that kind to declare: it is dirty when one of
                // the actions it joins is. It can still carry the chain's
                // unconditional flag, which is about whether the target can
                // ever settle, and reading that here would make the two sink
                // encodings disagree over a value neither path uses.
                deferred_freshness_always_dirty: !node.grouped_double_join
                    && node
                        .grouped_double_action
                        .as_ref()
                        .map_or(node.is_phony || node.unconditional_double_colon, |action| {
                            action.has_phony_member
                        }),
                deferred_always_new_inputs: &deferred_always_new_inputs,
                deferred_excluded_new_inputs: &deferred_excluded_new_inputs,
                completion_join: node.grouped_double_join,
                intermediate: node.is_intermediate,
                disposable: node.is_disposable,
                delete_on_error_outputs: &delete_on_error_outputs,
                peer_outputs: &peer_outputs,
                pool: pool.as_deref(),
                tags: tags.as_deref(),
                loc: node.loc.as_ref(),
            },
        )?;

        Ok(node.is_default_target.then_some(output))
    }

    /// Drive a sink through the whole graph.
    fn emit(&mut self, sink: &mut dyn BuildSink) -> Result<()> {
        sink.start(&[SinkPool {
            name: LOCAL_POOL,
            depth: self.ce.ev.session.flags.num_jobs,
        }])?;

        if !self.ce.ev.session.flags.generate_empty_ninja {
            let mut default_target = None;
            for node in std::mem::take(&mut self.nodes) {
                if let Some(output) = self.sink_node(&node, sink)? {
                    default_target = Some(output);
                }
            }

            // What the graph is aimed at is what dependency analysis resolved,
            // which is the goals the invocation named or the one
            // `.DEFAULT_GOAL` chose when it named none. Asking the evaluation
            // rather than the flags is what lets a default goal with no rule
            // of its own — a file that is simply already there — still be the
            // thing asked for, and it keeps a Makefile a front end has to
            // remake first from being mistaken for something to build.
            //
            // `--gen_all_targets` is the exception, because there every root
            // is a target and the manifest still wants one default: the first
            // rule of the read, which is what it meant before a goal could be
            // named at all.
            let targets = if self.ce.ev.session.flags.gen_all_targets {
                vec![default_target.unwrap()]
            } else {
                self.ce
                    .ev
                    .goals
                    .iter()
                    .map(|target| self.phony_aliases.resolve(*target))
                    .collect()
            };
            sink.set_default_targets(&self.ce.ev.session, &targets)?;
        }

        sink.finish()
    }

    fn get_env_script_filename(&self) -> OsString {
        ninja_file(&self.ce.ev.session.flags, "env", ".sh")
    }

    fn generate_ninja(&mut self) -> Result<()> {
        let _tr = ScopedTimeReporter::new(&self.ce.ev.session, "ninja gen (emit)");
        let out = std::fs::File::create(get_ninja_filename(&self.ce.ev.session.flags))?;
        let options = NinjaWriterOptions::from_flags(&self.ce.ev.session.flags);
        let mut sink = NinjaWriter::new(std::io::BufWriter::new(out), options);
        self.emit(&mut sink)?;

        // Collected after the manifest is written, for the stamp file that
        // decides whether a regeneration is needed. Upstream also writes these
        // into the manifest as a comment, from this same map, but does so
        // before filling it, so that comment has never once been emitted; both
        // C++ kati and this port have the same ordering. The block is not
        // reproduced in NinjaWriter, since feeding it would mean putting a
        // parameter on BuildSink for something unreachable.
        let mut used_env_vars = self.ce.ev.session.used_env_vars.clone();
        // PATH changes $(shell).
        used_env_vars.insert(self.ce.ev.session.intern("PATH"));
        for e in used_env_vars {
            let k = e.as_bytes(&self.ce.ev.session);
            let k = OsStr::from_bytes(&k);
            let val = std::env::var_os(k).unwrap();
            self.used_envs.insert(e, val);
        }

        Ok(())
    }

    fn generate_shell(&mut self) -> Result<()> {
        {
            let out = std::fs::File::create(self.get_env_script_filename())?;
            let mut out = std::io::BufWriter::new(out);

            writeln!(out, "#!/bin/sh")?;
            writeln!(out, "# Generated by kati unknown\n")?;

            let exports = self.ce.ev.exports.clone();
            for (symbol, is_exported) in exports {
                if is_exported {
                    let val = self.ce.ev.eval_var(symbol)?;
                    write!(out, "export '{}'='", symbol.display(&self.ce.ev.session))?;
                    out.write_all(&val)?;
                    writeln!(out, "'")?;
                } else {
                    writeln!(out, "unset '{}'", symbol.display(&self.ce.ev.session))?;
                }
            }
        }

        {
            let mut opts = OpenOptions::new();
            opts.create(true).write(true).mode(0o755);
            let out = opts.open(get_ninja_shell_script_filename(&self.ce.ev.session.flags))?;
            let mut out = std::io::BufWriter::new(out);

            writeln!(out, "#!/bin/sh")?;
            writeln!(out, "# Generated by kati unknown\n")?;

            write!(out, ". ")?;
            out.write_all(self.get_env_script_filename().as_bytes())?;

            write!(out, "\nexec ninja -f ")?;
            out.write_all(get_ninja_filename(&self.ce.ev.session.flags).as_bytes())?;
            out.write_all(b" ")?;
            if self.ce.ev.session.flags.remote_num_jobs > 0 {
                write!(out, "-j{} ", self.ce.ev.session.flags.remote_num_jobs)?;
            }
            writeln!(out, "\"$@\"")?;
        }
        Ok(())
    }

    fn generate_stamp(&self, orig_args: &[u8], start_time: SystemTime) -> Result<()> {
        {
            let out = std::fs::File::create(self.get_stamp_temp_filename())?;
            let mut out = std::io::BufWriter::new(out);

            dump_systemtime(&mut out, &start_time)?;

            let kati_binary = std::env::current_exe()?;
            let makefiles = self.ce.ev.session.makefiles.all_filenames();
            dump_usize(&mut out, makefiles.len() + 1)?;
            dump_string(&mut out, kati_binary.as_os_str().as_bytes())?;
            for makefile in makefiles {
                dump_string(&mut out, makefile.as_bytes())?;
            }

            let undefined = self.ce.ev.used_undefined_vars();
            dump_usize(&mut out, undefined.len())?;
            for v in &undefined {
                dump_string(&mut out, &v.as_bytes(&self.ce.ev.session))?;
            }
            dump_usize(&mut out, self.used_envs.len())?;
            for (key, value) in &self.used_envs {
                dump_string(&mut out, &key.as_bytes(&self.ce.ev.session))?;
                dump_string(&mut out, value.as_bytes())?;
            }

            let globs: Vec<(Bytes, crate::fileutil::GlobResults)> = self
                .ce
                .ev
                .session
                .glob_cache
                .recorded()
                .into_iter()
                .filter(|(_, files)| files.is_ok())
                .collect();
            dump_usize(&mut out, globs.len())?;
            for (key, files) in &globs {
                dump_string(&mut out, key)?;
                let Ok(files) = files.as_ref() else { continue };
                dump_vec_string(&mut out, files)?;
            }

            let crs = &self.ce.ev.session.command_results;
            dump_usize(&mut out, crs.len())?;
            for cr in crs.iter() {
                dump_int(&mut out, cr.op.as_int())?;
                dump_string(&mut out, &cr.shell)?;
                dump_string(&mut out, &cr.shellflag)?;
                dump_string(&mut out, &cr.cmd)?;
                dump_string(&mut out, &cr.result)?;
                dump_string(&mut out, &cr.loc.filename.as_bytes(&self.ce.ev.session))?;
                dump_int(&mut out, cr.loc.line)?;

                if cr.op == CommandOp::Find {
                    let fc = cr.find.as_ref().unwrap();
                    let chdir = fc.chdir.clone().unwrap_or_else(Bytes::new);
                    let mut missing_dirs = Vec::new();
                    for fd in &fc.finddirs {
                        let d = concat_dir(&chdir, fd);
                        if !std::fs::exists(OsStr::from_bytes(&d)).unwrap_or(false) {
                            missing_dirs.push(d);
                        }
                    }
                    dump_vec_string(&mut out, &missing_dirs)?;

                    dump_usize(&mut out, fc.found_files.lock().len())?;
                    for s in fc.found_files.lock().iter() {
                        dump_string(&mut out, &concat_dir(&chdir, s))?;
                    }

                    dump_usize(&mut out, fc.read_dirs.lock().len())?;
                    for s in fc.read_dirs.lock().iter() {
                        dump_string(&mut out, &concat_dir(&chdir, s))?;
                    }
                }
            }

            dump_string(&mut out, orig_args)?;
        }
        std::fs::rename(
            self.get_stamp_temp_filename(),
            get_ninja_stamp_filename(&self.ce.ev.session.flags),
        )?;
        Ok(())
    }
}

impl Drop for NinjaGenerator<'_> {
    fn drop(&mut self) {
        self.ce.ev.avoid_io = false;
        self.ce.ev.new_inputs_timing = NewInputsTiming::RecipeShell;
        self.ce.ev.shell_evaluation = ShellEvaluation::RecipeShell;
        self.ce.ev.deferred_new_inputs_filter_out.clear();
    }
}

/// Escape a name for a `build.ninja`, where `$`, `:` and space would otherwise
/// be syntax.
fn escape_ninja(s: &[u8]) -> Bytes {
    let extras = s.iter().filter(|c| b"$: ".contains(c)).count();
    if extras == 0 {
        return Bytes::copy_from_slice(s);
    }
    let mut r = BytesMut::with_capacity(s.len() + extras);
    for c in s {
        let c = *c;
        match c {
            b'$' | b':' | b' ' => {
                r.put_u8(b'$');
                r.put_u8(c);
            }
            _ => r.put_u8(c),
        }
    }
    r.freeze()
}

fn escape_build_target(names: &dyn Interner, s: Symbol) -> Bytes {
    escape_ninja(&s.as_bytes(&names))
}

/// Escape a value for the right-hand side of a `build.ninja` binding, where
/// `$` is the only character that is syntax.
///
/// A name in a `build` line needs [`escape_ninja`] instead, because there the
/// `:` and the space that separate names are syntax too. Here they are not, and
/// a command is mostly made of them.
///
/// Everything the front end hands the writer as *data* goes through this: the
/// command, the response-file content, the description, the depfile. Ninja
/// reverses it when it evaluates the binding, so what the build finally sees is
/// exactly the bytes that crossed the sink.
fn escape_ninja_value(s: &[u8]) -> Bytes {
    let extras = s.iter().filter(|c| **c == b'$').count();
    if extras == 0 {
        return Bytes::copy_from_slice(s);
    }
    let mut r = BytesMut::with_capacity(s.len() + extras);
    for c in s {
        if *c == b'$' {
            r.put_u8(b'$');
        }
        r.put_u8(*c);
    }
    r.freeze()
}

/// The flags that are about the manifest rather than about the build graph.
///
/// Pulling them out is what lets [`NinjaWriter`] own its own configuration
/// instead of borrowing the evaluator that is busy producing edges, and it
/// makes the list of purely-serialization options explicit: there are four.
pub struct NinjaWriterOptions {
    /// `-d`: annotate each stanza with the Makefile line it came from.
    pub locations: bool,
    /// The inverse of `--no_ninja_prelude`: write the `builddir`, pool and
    /// always-build declarations a standalone manifest needs. When it is off
    /// the caller is expected to supply them itself.
    pub prelude: bool,
    /// `--ninja_dir`: where ninja should keep its own state.
    pub builddir: Option<OsString>,
    /// `--use_ninja_phony_output`: Android's ninja fork can be told a target is
    /// not a file, which is a direct way to say what [`ALWAYS_BUILD`] otherwise
    /// has to fake.
    pub phony_output: bool,
}

impl NinjaWriterOptions {
    pub fn from_flags(flags: &Flags) -> Self {
        Self {
            locations: flags.enable_debug,
            prelude: !flags.no_ninja_prelude,
            builddir: flags.ninja_dir.clone(),
            phony_output: flags.use_ninja_phony_output,
        }
    }
}

/// The [`BuildSink`] that writes `build.ninja`.
///
/// Everything here is about the file format: escaping, the synthetic
/// always-build target, the prelude, and the spelling of each binding. Nothing
/// here decides anything about the build.
pub struct NinjaWriter<W: std::io::Write> {
    out: W,
    options: NinjaWriterOptions,
}

impl<W: std::io::Write> NinjaWriter<W> {
    pub fn new(out: W, options: NinjaWriterOptions) -> Self {
        Self { out, options }
    }

    fn write_location(&mut self, names: &dyn Interner, loc: Option<&Loc>) -> Result<()> {
        if self.options.locations {
            let loc = loc.cloned().unwrap_or_default();
            writeln!(self.out, "# {}", loc.display(names))?;
        }
        Ok(())
    }

    fn write_targets(&mut self, names: &dyn Interner, targets: &[Symbol]) -> Result<()> {
        for target in targets {
            self.out.write_all(b" ")?;
            self.out.write_all(&escape_build_target(names, *target))?;
        }
        Ok(())
    }
}

impl<W: std::io::Write> BuildSink for NinjaWriter<W> {
    fn start(&mut self, pools: &[SinkPool<'_>]) -> Result<()> {
        write!(self.out, "# Generated by kati unknown\n\n")?;

        if self.options.prelude {
            if let Some(builddir) = &self.options.builddir {
                write!(self.out, "builddir = ")?;
                self.out.write_all(builddir.as_bytes())?;
                self.out.write_all(b"\n\n")?;
            }

            for pool in pools {
                self.out.write_all(b"pool ")?;
                self.out.write_all(pool.name)?;
                writeln!(self.out, "\n depth = {}\n", pool.depth)?;
            }

            if !self.options.phony_output {
                self.out.write_all(b"build ")?;
                self.out.write_all(ALWAYS_BUILD)?;
                writeln!(self.out, ": phony\n")?;
            }
        }
        Ok(())
    }

    // [spec:ronin:req:make.state-outside-the-tree+2]
    fn declare_rule(&mut self, names: &dyn Interner, rule: &SinkRule<'_>) -> Result<()> {
        self.write_location(names, rule.loc)?;
        writeln!(self.out, "rule rule{}", rule.id)?;

        let description = rule.description.or(match rule.command {
            SinkCommand::Inline(script) => Some(script),
            SinkCommand::ResponseFile(_) => None,
        });
        if let Some(description) = description {
            self.out.write_all(b" description = ")?;
            self.out.write_all(&escape_ninja_value(description))?;
            self.out.write_all(b"\n")?;
        }

        if let Some(depfile) = rule.depfile {
            write!(self.out, " depfile = ")?;
            self.out.write_all(&escape_ninja_value(depfile))?;
            writeln!(self.out, "\n deps = gcc")?;
        }

        // Nothing in a manifest says an edge is allowed to fail, so the writer
        // is the one that answers for it: the script goes in a subshell, which
        // contains an `exit`, and the status is discarded outside it.
        let muted = rule.ignore_errors.then(|| {
            let script = match rule.command {
                SinkCommand::ResponseFile(script) | SinkCommand::Inline(script) => script,
            };
            [b"( ".as_slice(), script, b" ) ; true"].concat()
        });
        let command = match (&muted, &rule.command) {
            (Some(muted), SinkCommand::ResponseFile(_)) => SinkCommand::ResponseFile(muted),
            (Some(muted), SinkCommand::Inline(_)) => SinkCommand::Inline(muted),
            (None, command) => *command,
        };

        match command {
            // The script is the file, so the only layer between these bytes
            // and the shell is ninja's own.
            SinkCommand::ResponseFile(script) => {
                writeln!(self.out, " rspfile = {RESPONSE_FILE}")?;
                write!(self.out, " rspfile_content = ")?;
                self.out.write_all(&escape_ninja_value(script))?;
                write!(self.out, "\n command = ")?;
                self.out.write_all(&escape_ninja(rule.shell))?;
                writeln!(self.out, " {RESPONSE_FILE}")?;
            }
            // Two layers, and they have to be applied in this order. The
            // script becomes an argument of a shell ninja itself starts, so
            // first it is escaped for that shell; then the whole binding is
            // escaped for ninja, which unescapes it before the shell ever sees
            // it. A `$` the Makefile meant for the shell is therefore written
            // `\$$`: `\$` once ninja is done, `$` once the shell is.
            SinkCommand::Inline(script) => {
                self.out.write_all(b" command = ")?;
                self.out.write_all(&escape_ninja(rule.shell))?;
                self.out.write_all(b" ")?;
                self.out.write_all(&escape_ninja(rule.shell_flags))?;
                self.out.write_all(b" \"")?;
                self.out
                    .write_all(&escape_ninja_value(&escape_shell(&Bytes::copy_from_slice(
                        script,
                    ))))?;
                writeln!(self.out, "\"")?;
            }
        }

        // GNU Make uses timestamps, not a persisted recipe hash, to decide
        // whether a current target needs rebuilding. `generator` carries that
        // policy in the emitted Ninja graph just as GraphSink does directly.
        writeln!(self.out, " generator = 1")?;
        if rule.restat {
            writeln!(self.out, " restat = 1")?;
        }
        if rule.sandbox_disabled {
            writeln!(self.out, " sandbox_disabled = true")?;
        }
        Ok(())
    }

    fn declare_edge(&mut self, names: &dyn Interner, edge: &SinkEdge<'_>) -> Result<()> {
        // A node with a rule already had its location printed above the rule.
        if edge.rule.is_none() {
            self.write_location(names, edge.loc)?;
        }

        write!(self.out, "build ")?;
        self.out
            .write_all(&escape_build_target(names, edge.output))?;
        if !edge.implicit_outputs.is_empty() {
            write!(self.out, " |")?;
            self.write_targets(names, edge.implicit_outputs)?;
        }

        match edge.rule {
            Some(id) => write!(self.out, ": rule{id}")?,
            None => write!(self.out, ": phony")?,
        }

        // A .PHONY target has to look dirty to a tool that only compares file
        // timestamps. Depending on a target nothing ever builds is how the
        // manifest arranges that; it is not something the graph knows about.
        if edge.always_dirty && !self.options.phony_output {
            self.out.write_all(b" ")?;
            self.out.write_all(ALWAYS_BUILD)?;
        }

        self.write_targets(names, edge.inputs)?;
        if !edge.order_only_inputs.is_empty() {
            write!(self.out, " ||")?;
            self.write_targets(names, edge.order_only_inputs)?;
        }
        if !edge.validations.is_empty() {
            write!(self.out, " |@")?;
            self.write_targets(names, edge.validations)?;
        }
        writeln!(self.out)?;

        if let Some(pool) = edge.pool {
            write!(self.out, " pool = ")?;
            self.out.write_all(pool)?;
            self.out.write_all(b"\n")?;
        }
        if edge.always_dirty && self.options.phony_output {
            writeln!(self.out, " phony_output = true")?;
        }
        if let Some(tags) = edge.tags {
            write!(self.out, " tags = ")?;
            self.out.write_all(tags)?;
            writeln!(self.out)?;
        }
        Ok(())
    }

    fn set_default_targets(&mut self, names: &dyn Interner, targets: &[Symbol]) -> Result<()> {
        write!(self.out, "\ndefault")?;
        self.write_targets(names, targets)?;
        self.out.write_all(b"\n")?;
        Ok(())
    }

    fn finish(&mut self) -> Result<()> {
        self.out.flush()?;
        Ok(())
    }
}

pub fn get_ninja_filename(flags: &Flags) -> OsString {
    ninja_file(flags, "build", ".ninja")
}

pub fn get_ninja_shell_script_filename(flags: &Flags) -> OsString {
    ninja_file(flags, "ninja", ".sh")
}

pub fn get_ninja_stamp_filename(flags: &Flags) -> OsString {
    ninja_file(flags, ".kati_stamp", "")
}

fn ninja_file(flags: &Flags, prefix: &str, suffix: &str) -> OsString {
    let mut r = flags
        .ninja_dir
        .clone()
        .unwrap_or_else(|| OsString::from("."));
    r.push("/");
    r.push(prefix);
    r.push(&flags.ninja_suffix);
    r.push(suffix);
    r
}

pub fn generate_ninja(
    nodes: &Vec<NamedDepNode>,
    ev: &mut Evaluator,
    orig_args: &[u8],
    start_time: SystemTime,
) -> Result<()> {
    let mut ng = NinjaGenerator::new(
        CommandEvaluator::new(
            ev,
            NewInputsTiming::RecipeShell,
            ShellEvaluation::RecipeShell,
        )?,
        RecipeExpansion::Construction,
    )?;
    ng.generate(nodes, orig_args, start_time)?;
    Ok(())
}

/// Hand the graph `nodes` describes to `sink`, and write nothing.
///
/// [`generate_ninja`] is this with [`NinjaWriter`] already chosen, plus the
/// three files that only a manifest needs: the environment script, the wrapper
/// that runs ninja under it, and the stamp a regeneration check reads. A front
/// end that consumes the graph in memory wants none of those, so this is the
/// whole of what it needs — the same walk, the same commands, the same edges,
/// with the destination left to the caller.
// [spec:ronin:req:make.graph-direct]
pub fn emit_build(
    nodes: &Vec<NamedDepNode>,
    ev: &mut Evaluator,
    sink: &mut dyn BuildSink,
) -> Result<DeferredRecipes> {
    let new_inputs_timing = sink.new_inputs_timing();
    let shell_evaluation = sink.shell_evaluation();
    let recipe_expansion = sink.recipe_expansion();
    let mut ng = NinjaGenerator::new(
        CommandEvaluator::new(ev, new_inputs_timing, shell_evaluation)?,
        recipe_expansion,
    )?;
    ng.populate_ninja_nodes(nodes)?;
    ng.emit(sink)?;
    Ok(DeferredRecipes {
        recipes: std::mem::take(&mut ng.deferred_recipes),
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::symtab::Symtab;

    /// Drive a writer over one always-dirty edge whose names need escaping.
    fn write_phony_edge(phony_output: bool) -> String {
        let mut names = Symtab::new();
        let output = names.intern(&b"out:put"[..]);
        let input = names.intern(&b"in$put"[..]);
        let mut writer = NinjaWriter::new(
            Vec::new(),
            NinjaWriterOptions {
                locations: false,
                prelude: true,
                builddir: None,
                phony_output,
            },
        );
        writer
            .start(&[SinkPool {
                name: LOCAL_POOL,
                depth: 4,
            }])
            .unwrap();
        writer
            .declare_edge(
                &names,
                &SinkEdge {
                    rule: None,
                    output,
                    implicit_outputs: &[],
                    inputs: &[input],
                    order_only_inputs: &[],
                    validations: &[],
                    always_dirty: true,
                    deferred_freshness_outputs: &[],
                    deferred_freshness_always_dirty: false,
                    deferred_always_new_inputs: &[],
                    deferred_excluded_new_inputs: &[],
                    completion_join: false,
                    intermediate: false,
                    disposable: false,
                    delete_on_error_outputs: &[],
                    peer_outputs: &[],
                    pool: None,
                    tags: None,
                    loc: None,
                },
            )
            .unwrap();
        writer.set_default_targets(&names, &[output]).unwrap();
        writer.finish().unwrap();
        String::from_utf8(writer.out).unwrap()
    }

    /// The synthetic always-build target is the writer's invention, not
    /// something the front end pushed through the sink: the same edge, said
    /// the same way, produces it or `phony_output` depending only on how the
    /// writer was configured.
    #[test]
    fn test_writer_owns_the_always_dirty_mechanism() {
        let synthetic = write_phony_edge(false);
        assert!(
            synthetic.contains("build _kati_always_build_: phony\n"),
            "{synthetic}"
        );
        assert!(
            synthetic.contains("build out$:put: phony _kati_always_build_ in$$put\n"),
            "{synthetic}"
        );
        assert!(!synthetic.contains("phony_output"), "{synthetic}");

        let declared = write_phony_edge(true);
        assert!(!declared.contains("_kati_always_build_"), "{declared}");
        assert!(
            declared.contains("build out$:put: phony in$$put\n phony_output = true\n"),
            "{declared}"
        );
    }

    /// Escaping happens on the way out and nowhere earlier, so the same
    /// unescaped symbol is escaped consistently everywhere it appears.
    #[test]
    fn test_writer_escapes_every_name_it_writes() {
        let out = write_phony_edge(false);
        assert!(out.contains("\ndefault out$:put\n"), "{out}");
        assert!(!out.contains("out:put"), "{out}");
    }

    fn get_desc(cmd: &'static [u8]) -> Option<String> {
        NinjaGenerator::get_description_from_command(&Bytes::from_static(cmd))
            .map(|d| String::from_utf8_lossy(d.as_ref()).to_string())
    }

    #[test]
    fn test_get_description_from_command() {
        assert_eq!(get_desc(b"echo Hello"), Some("Hello".into()));
        assert_eq!(
            get_desc(b"echo \"Hello 'World'\""),
            Some("Hello 'World'".into())
        );
        assert_eq!(
            get_desc(b"echo Hello \\\" World"),
            Some("Hello \\\" World".into())
        );
    }

    #[test]
    fn test_translate_command() {
        assert_eq!(
            NinjaGenerator::translate_command(Bytes::from_static(b"echo Hello")),
            Bytes::from_static(b"echo Hello")
        );
        // Make's own escape is long gone by here, so a `$` is the shell's and
        // translation leaves it alone.
        assert_eq!(
            NinjaGenerator::translate_command(Bytes::from_static(b"echo $PATH")),
            Bytes::from_static(b"echo $PATH")
        );
    }

    /// The script and the ignore-errors flag `sink_node` would hand to a sink
    /// for a recipe whose lines are `(expansion, whether errors are ignored)`.
    fn recipe_script(lines: &[(&'static [u8], bool)]) -> (Bytes, bool) {
        let posix: Vec<(&'static [u8], bool)> = lines
            .iter()
            .map(|(cmd, ignored)| (*cmd, *ignored))
            .collect();
        script_of(&posix, false).0
    }

    /// As [`recipe_script`], and additionally the flags the script runs under.
    ///
    /// `posix` says the recipe was read under `.POSIX:`, which is what makes a
    /// `-` prefix ask for different flags than the line beside it.
    fn script_of(lines: &[(&'static [u8], bool)], posix: bool) -> ((Bytes, bool), Bytes) {
        let mut names = Symtab::new();
        let output = names.intern(&b"out"[..]);
        let commands: Vec<Command> = lines
            .iter()
            .map(|(cmd, dash_prefixed)| Command {
                output,
                cmd: Bytes::from_static(cmd),
                echo: true,
                ignore_error: *dash_prefixed,
                dash_prefixed: *dash_prefixed,
                shell_flag: Bytes::from_static(match (posix, dash_prefixed) {
                    (true, false) => b"-ec",
                    _ => b"-c",
                }),
                force_no_subshell: false,
                recursive_line: false,
                recursive_make: Vec::new(),
                uncomposable_recursion: false,
            })
            .collect();
        let flags = Flags::default();
        let script_flags = NinjaGenerator::script_shell_flags(&flags, &commands);
        let mut cmd_buf = BytesMut::new();
        let mut description = None;
        let ignore_errors = NinjaGenerator::gen_shell_script(
            &flags,
            &Bytes::from_static(b"out"),
            &commands,
            &script_flags,
            &mut cmd_buf,
            &mut description,
        );
        assert_eq!(description, None, "no Makefile echo, so no description");
        ((cmd_buf.freeze(), ignore_errors), script_flags)
    }

    /// The script for a one-line recipe whose errors are nobody's to ignore.
    fn script_for(cmd: &'static [u8]) -> Bytes {
        recipe_script(&[(cmd, false)]).0
    }

    /// The manifest stanza a writer produces for one rule.
    fn declare_rule_for(command: SinkCommand<'_>, description: Option<&[u8]>) -> String {
        declare_rule_of(command, description, false)
    }

    fn declare_rule_of(
        command: SinkCommand<'_>,
        description: Option<&[u8]>,
        ignore_errors: bool,
    ) -> String {
        let names = Symtab::new();
        let mut writer = NinjaWriter::new(
            Vec::new(),
            NinjaWriterOptions {
                locations: false,
                prelude: false,
                builddir: None,
                phony_output: false,
            },
        );
        writer
            .declare_rule(
                &names,
                &SinkRule {
                    id: 0,
                    shell: b"/bin/sh",
                    shell_flags: b"-c",
                    command,
                    deferred_recipe: None,
                    subninjas: &[],
                    contains_recursive: false,
                    residual_command: None,
                    residual_ignore_errors: false,
                    description,
                    depfile: None,
                    restat: false,
                    ignore_errors,
                    sandbox_disabled: false,
                    loc: None,
                },
            )
            .unwrap();
        String::from_utf8(writer.out).unwrap()
    }

    fn binding(manifest: &str, name: &str) -> String {
        let prefix = format!(" {name} = ");
        manifest
            .lines()
            .find_map(|l| l.strip_prefix(prefix.as_str()))
            .unwrap_or_else(|| panic!("no {name} in {manifest}"))
            .to_string()
    }

    /// What ninja makes of a binding's value, which is what the build actually
    /// runs. Panics on a `$` it cannot account for, since that is the shape the
    /// escaping exists to avoid: an unescaped `$` in a manifest is a variable
    /// reference, and expands to nothing.
    fn ninja_unescape(value: &[u8]) -> Vec<u8> {
        let mut out = Vec::new();
        let mut rest = value;
        while let Some((c, tail)) = rest.split_first() {
            rest = tail;
            if *c != b'$' {
                out.push(*c);
                continue;
            }
            match rest.split_first() {
                Some((c @ (b'$' | b':' | b' '), tail)) => {
                    out.push(*c);
                    rest = tail;
                }
                other => panic!("unescaped $ before {other:?} in {value:?}"),
            }
        }
        out
    }

    /// What a shell makes of the inside of a `"..."` argument.
    fn shell_unquote(quoted: &[u8]) -> Vec<u8> {
        let mut out = Vec::new();
        let mut rest = quoted;
        while let Some((c, tail)) = rest.split_first() {
            rest = tail;
            match (c, rest.first()) {
                (b'\\', Some(next @ (b'"' | b'$' | b'\\' | b'`'))) => {
                    out.push(*next);
                    rest = &rest[1..];
                }
                _ => out.push(*c),
            }
        }
        out
    }

    /// What crosses the sink is what the *shell* is meant to receive, not what
    /// a manifest is meant to contain.
    ///
    /// A manifest cannot tell the two apart: ninja unescapes on the way in, so
    /// a command that was escaped one time too many still reaches the shell
    /// correctly through `build.ninja`, and only a sink that writes the bytes
    /// straight into a graph sees the difference. This pins the boundary from
    /// both sides — the bytes are the shell's, and every escape between them
    /// and the file undoes exactly.
    #[test]
    fn test_command_crosses_the_sink_as_a_shell_wants_it() {
        // What Make's evaluator produces for a recipe line reading
        // `echo $$PATH`: Make's escape is already gone, and the shell is meant
        // to expand PATH.
        let script = script_for(b"echo $PATH");
        assert_eq!(script, Bytes::from_static(b"echo $PATH"));

        // Inline: escaped for the shell ninja starts, then for ninja itself.
        let manifest = declare_rule_for(SinkCommand::Inline(&script), None);
        let evaluated = ninja_unescape(binding(&manifest, "command").as_bytes());
        assert_eq!(evaluated, b"/bin/sh -c \"echo \\$PATH\"");
        let quoted = evaluated
            .strip_prefix(b"/bin/sh -c \"")
            .and_then(|v| v.strip_suffix(b"\""))
            .unwrap();
        assert_eq!(shell_unquote(quoted), script);

        // A response file is read by the shell directly, so ninja's is the
        // only escape between the two.
        let manifest = declare_rule_for(SinkCommand::ResponseFile(&script), None);
        assert_eq!(
            ninja_unescape(binding(&manifest, "rspfile_content").as_bytes()),
            script
        );
        assert_eq!(binding(&manifest, "rspfile"), RESPONSE_FILE);
    }

    /// A description the Makefile chose is text and gets escaped. Without one,
    /// use a short inline recipe itself, but do not duplicate an oversized
    /// response-file script into the build's narration.
    #[test]
    fn test_writer_uses_the_inline_recipe_as_its_default_description() {
        let manifest = declare_rule_for(SinkCommand::Inline(b"true"), None);
        assert_eq!(binding(&manifest, "description"), "true");

        let manifest = declare_rule_for(SinkCommand::ResponseFile(b"true"), None);
        assert!(!manifest.contains(" description = "), "{manifest}");

        let manifest = declare_rule_for(SinkCommand::Inline(b"true"), Some(b"making $PATH"));
        assert_eq!(binding(&manifest, "description"), "making $$PATH");
        assert_eq!(
            ninja_unescape(binding(&manifest, "description").as_bytes()),
            b"making $PATH"
        );
    }

    // [spec:ronin:req:make.state-outside-the-tree+2/test]
    #[test]
    fn writer_marks_recipes_timestamp_only() {
        let manifest = declare_rule_for(SinkCommand::Inline(b"true"), None);
        assert_eq!(binding(&manifest, "generator"), "1");
    }

    /// `exit` leaves a subshell before anything after it inside runs, so the
    /// status is dropped outside the subshell or it is not dropped at all.
    #[test]
    fn an_ignored_line_lets_the_rest_of_the_recipe_run_even_past_exit() {
        let (script, ignore_errors) = recipe_script(&[(b"exit 1", true), (b"echo ok", false)]);
        assert_eq!(
            script,
            Bytes::from_static(b"{ (exit 1 ) ; true ; } && (echo ok )")
        );
        assert!(!ignore_errors, "only one of the two lines ignores errors");
    }

    /// The group is what keeps the muting local: a bare `; true` would swallow
    /// the chain's own break as well as the line it was written for.
    #[test]
    fn a_line_whose_failure_counts_still_stops_a_recipe_that_ignores_another() {
        let (script, ignore_errors) = recipe_script(&[(b"false", false), (b"exit 3", true)]);
        assert_eq!(
            script,
            Bytes::from_static(b"(false ) && { (exit 3 ) ; true ; }")
        );
        assert!(!ignore_errors);
    }

    /// Nothing here can fail in a way that counts, so the status is left alone
    /// and the sink is told it may read a nonzero one as an ignored error.
    #[test]
    fn a_wholly_ignored_recipe_keeps_the_status_it_ends_on() {
        let (script, ignore_errors) = recipe_script(&[(b"false", true), (b"exit 3", true)]);
        assert_eq!(script, Bytes::from_static(b"(false ) ; (exit 3 )"));
        assert!(ignore_errors);
    }

    /// GNU Make gives the prefixed line a shell without `-e` and the plain one
    /// beside it a shell with it. One invocation cannot have both, so the
    /// strict flags govern and the prefixed line takes `-e` back off inside
    /// its own subshell, where it reaches nothing else.
    #[test]
    fn posix_relaxes_only_the_prefixed_line() {
        let ((script, _), flags) = script_of(
            &[(b"false ; echo body > out", true), (b"echo done", false)],
            true,
        );
        assert_eq!(flags, Bytes::from_static(b"-ec"));
        assert_eq!(
            script,
            Bytes::from_static(b"{ (set +e ; false ; echo body > out ) ; true ; } && (echo done )")
        );
    }

    /// With no plain line to keep strict there is nothing to accommodate, so
    /// the relaxed flags govern and no line has to undo them.
    #[test]
    fn posix_drops_errexit_for_a_wholly_prefixed_recipe() {
        let ((script, ignore_errors), flags) =
            script_of(&[(b"false ; echo body > out", true)], true);
        assert_eq!(flags, Bytes::from_static(b"-c"));
        assert_eq!(script, Bytes::from_static(b"(false ; echo body > out )"));
        assert!(ignore_errors);
    }

    /// Without `.POSIX:` every line already wanted the same shell, so the
    /// accommodation never appears and the script reads as it always did.
    #[test]
    fn a_plain_recipe_never_relaxes_a_line() {
        let ((script, _), flags) = script_of(&[(b"false", true), (b"echo done", false)], false);
        assert_eq!(flags, Bytes::from_static(b"-c"));
        assert!(!script.windows(3).any(|w| w == b"set"), "{script:?}");
    }

    /// A manifest cannot say an edge is allowed to fail, so the writer says it
    /// in the only place it can.
    #[test]
    fn the_manifest_writer_discards_an_ignored_status_itself() {
        let manifest = declare_rule_of(SinkCommand::Inline(b"( false )"), None, true);
        let evaluated = ninja_unescape(binding(&manifest, "command").as_bytes());
        assert_eq!(evaluated, b"/bin/sh -c \"( ( false ) ) ; true\"");

        let manifest = declare_rule_of(SinkCommand::ResponseFile(b"( false )"), None, true);
        assert_eq!(
            ninja_unescape(binding(&manifest, "rspfile_content").as_bytes()),
            b"( ( false ) ) ; true"
        );
    }

    fn get_depfile_and_cmd(cmd: &str) -> Result<(Option<String>, String)> {
        let mut cmd = BytesMut::from(cmd.as_bytes());
        let depfile = get_depfile_from_command(&mut cmd)?;
        Ok((
            depfile.map(|b| String::from_utf8_lossy(&b).to_string()),
            String::from_utf8_lossy(&cmd).to_string(),
        ))
    }
    fn get_depfile(cmd: &str) -> Result<Option<String>> {
        Ok(get_depfile_and_cmd(cmd)?.0)
    }

    #[test]
    fn test_get_depfile() -> Result<()> {
        assert!(get_depfile("g++ -c fat.cc -MD ").is_err());

        assert_eq!(get_depfile("g++ -c fat.cc -o fat.o")?, None);
        assert_eq!(
            get_depfile("g++ -c fat.cc -MD -o fat.o -o fuga.o")?,
            Some("fuga.d.tmp".into())
        );
        assert_eq!(
            get_depfile("g++ -c fat.cc -MD -o fat.o")?,
            Some("fat.d.tmp".into())
        );
        assert_eq!(
            get_depfile("g++ -c fat.cc -MD -o fat")?,
            Some("fat.d.tmp".into())
        );
        assert_eq!(
            get_depfile("g++ -c fat.cc -MD -MF foo.d -o fat.o")?,
            Some("foo.d.tmp".into())
        );
        assert_eq!(
            get_depfile("g++ -c fat.cc -MD -o fat.o -MF foo.d")?,
            Some("foo.d.tmp".into())
        );
        // A real example from maloader.
        assert_eq!(
            get_depfile(
                "g++ -g -Iinclude -Wall -MMD -fno-omit-frame-pointer -O -m64 -W -Werror   -c -o fat.o fat.cc"
            )?,
            Some("fat.d.tmp".into())
        );
        // A real example from Android.
        assert_eq!(
            get_depfile_and_cmd(
                "mkdir -p out/host/linux-x86/obj/EXECUTABLES/llvm-rs-cc_intermediates/ && echo \"host C++: llvm-rs-cc <= frameworks/compile/slang/llvm-rs-cc.cpp\" && prebuilts/clang/linux-x86/host/3.6/bin/clang++ -I external/llvm -I external/llvm/include -I external/llvm/host/include -I external/clang/include -I external/clang/lib/CodeGen -I frameworks/compile/libbcc/include -I out/host/linux-x86/gen/EXECUTABLES/llvm-rs-cc_intermediates/include -I external/libcxx/include -I frameworks/compile/slang -I out/host/linux-x86/obj/EXECUTABLES/llvm-rs-cc_intermediates -I out/host/linux-x86/gen/EXECUTABLES/llvm-rs-cc_intermediates -I libnativehelper/include/nativehelper $(cat out/host/linux-x86/obj/EXECUTABLES/llvm-rs-cc_intermediates/import_includes) -isystem system/core/include -isystem hardware/libhardware/include -isystem hardware/libhardware_legacy/include -isystem hardware/ril/include -isystem libnativehelper/include -isystem frameworks/native/include -isystem frameworks/native/opengl/include -isystem frameworks/av/include -isystem frameworks/base/include -isystem tools/include -isystem out/host/linux-x86/obj/include -c    -fno-exceptions -Wno-multichar -m64 -Wa,--noexecstack -fPIC -no-canonical-prefixes -include build/core/combo/include/arch/linux-x86/AndroidConfig.h -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -D__STDC_FORMAT_MACROS -D__STDC_CONSTANT_MACROS -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -O2 -g -fno-strict-aliasing -DNDEBUG -UDEBUG  -D__compiler_offsetof=__builtin_offsetof -Werror=int-conversion -Wno-unused-command-line-argument   --gcc-toolchain=prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.15-4.8/    --gcc-toolchain=prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.15-4.8/ --sysroot=prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.15-4.8//sysroot -target x86_64-linux-gnu   -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -Wsign-promo -std=gnu++11 -DNDEBUG -UDEBUG  -Wno-inconsistent-missing-override   --gcc-toolchain=prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.15-4.8/ --sysroot=prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.15-4.8//sysroot -isystem prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.15-4.8//x86_64-linux/include/c++/4.8 -isystem prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.15-4.8//x86_64-linux/include/c++/4.8/x86_64-linux -isystem prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.15-4.8//x86_64-linux/include/c++/4.8/backward -target x86_64-linux-gnu    -pedantic -Wcast-qual -Wno-long-long -Wno-sign-promo -Wall -Wno-unused-parameter -Wno-return-type -Werror -std=c++11 -O0 -DTARGET_BUILD_VARIANT=eng -DRS_VERSION=23 -D_GNU_SOURCE -D__STDC_LIMIT_MACROS -O2 -fomit-frame-pointer -Wall -W -Wno-unused-parameter -Wwrite-strings -Dsprintf=sprintf -pedantic -Wcast-qual -Wno-long-long -Wno-sign-promo -Wall -Wno-unused-parameter -Wno-return-type -Werror -std=c++11 -O0 -DTARGET_BUILD_VARIANT=eng -DRS_VERSION=23 -fno-exceptions -fpie -D_USING_LIBCXX   -Wno-sign-promo -fno-rtti -Woverloaded-virtual -Wno-sign-promo -std=c++11 -nostdinc++  -MD -MF out/host/linux-x86/obj/EXECUTABLES/llvm-rs-cc_intermediates/llvm-rs-cc.d -o out/host/linux-x86/obj/EXECUTABLES/llvm-rs-cc_intermediates/llvm-rs-cc.o frameworks/compile/slang/llvm-rs-cc.cpp && cp out/host/linux-x86/obj/EXECUTABLES/llvm-rs-cc_intermediates/llvm-rs-cc.d out/host/linux-x86/obj/EXECUTABLES/llvm-rs-cc_intermediates/llvm-rs-cc.P; sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$//' -e '/^$/ d' -e 's/$/ :/' < out/host/linux-x86/obj/EXECUTABLES/llvm-rs-cc_intermediates/llvm-rs-cc.d >> out/host/linux-x86/obj/EXECUTABLES/llvm-rs-cc_intermediates/llvm-rs-cc.P; rm -f out/host/linux-x86/obj/EXECUTABLES/llvm-rs-cc_intermediates/llvm-rs-cc.d"
            )?,
            (
                Some("out/host/linux-x86/obj/EXECUTABLES/llvm-rs-cc_intermediates/llvm-rs-cc.d".into()),
                "mkdir -p out/host/linux-x86/obj/EXECUTABLES/llvm-rs-cc_intermediates/ && echo \"host C++: llvm-rs-cc <= frameworks/compile/slang/llvm-rs-cc.cpp\" && prebuilts/clang/linux-x86/host/3.6/bin/clang++ -I external/llvm -I external/llvm/include -I external/llvm/host/include -I external/clang/include -I external/clang/lib/CodeGen -I frameworks/compile/libbcc/include -I out/host/linux-x86/gen/EXECUTABLES/llvm-rs-cc_intermediates/include -I external/libcxx/include -I frameworks/compile/slang -I out/host/linux-x86/obj/EXECUTABLES/llvm-rs-cc_intermediates -I out/host/linux-x86/gen/EXECUTABLES/llvm-rs-cc_intermediates -I libnativehelper/include/nativehelper $(cat out/host/linux-x86/obj/EXECUTABLES/llvm-rs-cc_intermediates/import_includes) -isystem system/core/include -isystem hardware/libhardware/include -isystem hardware/libhardware_legacy/include -isystem hardware/ril/include -isystem libnativehelper/include -isystem frameworks/native/include -isystem frameworks/native/opengl/include -isystem frameworks/av/include -isystem frameworks/base/include -isystem tools/include -isystem out/host/linux-x86/obj/include -c    -fno-exceptions -Wno-multichar -m64 -Wa,--noexecstack -fPIC -no-canonical-prefixes -include build/core/combo/include/arch/linux-x86/AndroidConfig.h -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -D__STDC_FORMAT_MACROS -D__STDC_CONSTANT_MACROS -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -O2 -g -fno-strict-aliasing -DNDEBUG -UDEBUG  -D__compiler_offsetof=__builtin_offsetof -Werror=int-conversion -Wno-unused-command-line-argument   --gcc-toolchain=prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.15-4.8/    --gcc-toolchain=prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.15-4.8/ --sysroot=prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.15-4.8//sysroot -target x86_64-linux-gnu   -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -Wsign-promo -std=gnu++11 -DNDEBUG -UDEBUG  -Wno-inconsistent-missing-override   --gcc-toolchain=prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.15-4.8/ --sysroot=prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.15-4.8//sysroot -isystem prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.15-4.8//x86_64-linux/include/c++/4.8 -isystem prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.15-4.8//x86_64-linux/include/c++/4.8/x86_64-linux -isystem prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.15-4.8//x86_64-linux/include/c++/4.8/backward -target x86_64-linux-gnu    -pedantic -Wcast-qual -Wno-long-long -Wno-sign-promo -Wall -Wno-unused-parameter -Wno-return-type -Werror -std=c++11 -O0 -DTARGET_BUILD_VARIANT=eng -DRS_VERSION=23 -D_GNU_SOURCE -D__STDC_LIMIT_MACROS -O2 -fomit-frame-pointer -Wall -W -Wno-unused-parameter -Wwrite-strings -Dsprintf=sprintf -pedantic -Wcast-qual -Wno-long-long -Wno-sign-promo -Wall -Wno-unused-parameter -Wno-return-type -Werror -std=c++11 -O0 -DTARGET_BUILD_VARIANT=eng -DRS_VERSION=23 -fno-exceptions -fpie -D_USING_LIBCXX   -Wno-sign-promo -fno-rtti -Woverloaded-virtual -Wno-sign-promo -std=c++11 -nostdinc++  -MD -MF out/host/linux-x86/obj/EXECUTABLES/llvm-rs-cc_intermediates/llvm-rs-cc.d -o out/host/linux-x86/obj/EXECUTABLES/llvm-rs-cc_intermediates/llvm-rs-cc.o frameworks/compile/slang/llvm-rs-cc.cpp && cp out/host/linux-x86/obj/EXECUTABLES/llvm-rs-cc_intermediates/llvm-rs-cc.d out/host/linux-x86/obj/EXECUTABLES/llvm-rs-cc_intermediates/llvm-rs-cc.P; sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$//' -e '/^$/ d' -e 's/$/ :/' < out/host/linux-x86/obj/EXECUTABLES/llvm-rs-cc_intermediates/llvm-rs-cc.d >> out/host/linux-x86/obj/EXECUTABLES/llvm-rs-cc_intermediates/llvm-rs-cc.P".into()
            )
        );
        assert_eq!(
            get_depfile(
                "echo \"target asm: libsonivox <= external/sonivox/arm-wt-22k/lib_src/ARM-E_filter_gnu.s\" && mkdir -p out/target/product/generic/obj/SHARED_LIBRARIES/libsonivox_intermediates/lib_src/ && prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/bin/arm-linux-androideabi-gcc -I external/sonivox/arm-wt-22k/host_src -I external/sonivox/arm-wt-22k/lib_src -I external/libcxx/include -I external/sonivox/arm-wt-22k -I out/target/product/generic/obj/SHARED_LIBRARIES/libsonivox_intermediates -I out/target/product/generic/gen/SHARED_LIBRARIES/libsonivox_intermediates -I libnativehelper/include/nativehelper $$(cat out/target/product/generic/obj/SHARED_LIBRARIES/libsonivox_intermediates/import_includes) -isystem system/core/include -isystem hardware/libhardware/include -isystem hardware/libhardware_legacy/include -isystem hardware/ril/include -isystem libnativehelper/include -isystem frameworks/native/include -isystem frameworks/native/opengl/include -isystem frameworks/av/include -isystem frameworks/base/include -isystem out/target/product/generic/obj/include -isystem bionic/libc/arch-arm/include -isystem bionic/libc/include -isystem bionic/libc/kernel/uapi -isystem bionic/libc/kernel/uapi/asm-arm -isystem bionic/libm/include -isystem bionic/libm/include/arm -c  -fno-exceptions -Wno-multichar -msoft-float -ffunction-sections -fdata-sections -funwind-tables -fstack-protector -Wa,--noexecstack -Werror=format-security -D_FORTIFY_SOURCE=2 -fno-short-enums -no-canonical-prefixes -fno-canonical-system-headers -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -include build/core/combo/include/arch/linux-arm/AndroidConfig.h -I build/core/combo/include/arch/linux-arm/ -fno-builtin-sin -fno-strict-volatile-bitfields -Wno-psabi -mthumb-interwork -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -DNDEBUG -g -Wstrict-aliasing=2 -fgcse-after-reload -frerun-cse-after-loop -frename-registers -DNDEBUG -UDEBUG     -Wa,\"-I\" -Wa,\"external/sonivox/arm-wt-22k/lib_src\" -Wa,\"--defsym\" -Wa,\"SAMPLE_RATE_22050=1\" -Wa,\"--defsym\" -Wa,\"STEREO_OUTPUT=1\" -Wa,\"--defsym\" -Wa,\"FILTER_ENABLED=1\" -Wa,\"--defsym\" -Wa,\"SAMPLES_8_BIT=1\"   -D__ASSEMBLY__ -MD -MF out/target/product/generic/obj/SHARED_LIBRARIES/libsonivox_intermediates/lib_src/ARM-E_filter_gnu.d -o out/target/product/generic/obj/SHARED_LIBRARIES/libsonivox_intermediates/lib_src/ARM-E_filter_gnu.o external/sonivox/arm-wt-22k/lib_src/ARM-E_filter_gnu.s"
            )?,
            None
        );
        assert_eq!(
            get_depfile(
                "echo \"RenderScript: Galaxy4 <= packages/wallpapers/Galaxy4/src/com/android/galaxy4/galaxy.rs\" && rm -rf out/target/common/obj/APPS/Galaxy4_intermediates/src/renderscript && mkdir -p out/target/common/obj/APPS/Galaxy4_intermediates/src/renderscript/res/raw && mkdir -p out/target/common/obj/APPS/Galaxy4_intermediates/src/renderscript/src && out/host/linux-x86/bin/llvm-rs-cc -o out/target/common/obj/APPS/Galaxy4_intermediates/src/renderscript/res/raw -p out/target/common/obj/APPS/Galaxy4_intermediates/src/renderscript/src -d out/target/common/obj/APPS/Galaxy4_intermediates/src/renderscript -a out/target/common/obj/APPS/Galaxy4_intermediates/src/RenderScript.stamp -MD -target-api 14 -Wall -Werror  -I prebuilts/sdk/renderscript/clang-include -I prebuilts/sdk/renderscript/include packages/wallpapers/Galaxy4/src/com/android/galaxy4/galaxy.rs && mkdir -p out/target/common/obj/APPS/Galaxy4_intermediates/src/ && touch out/target/common/obj/APPS/Galaxy4_intermediates/src/RenderScript.stamp"
            )?,
            None
        );
        assert_eq!(
            get_depfile_and_cmd(
                "(echo \"bc: libclcore.bc <= frameworks/rs/driver/runtime/arch/generic.c\") && (mkdir -p out/target/product/generic/obj/SHARED_LIBRARIES/libclcore.bc_intermediates/arch/) && (prebuilts/clang/linux-x86/host/3.6/bin/clang -Iframeworks/rs/scriptc -Iexternal/clang/lib/Headers -MD -DRS_VERSION=23 -std=c99 -c -O3 -fno-builtin -emit-llvm -target armv7-none-linux-gnueabi -fsigned-char   -Iframeworks/rs/cpu_ref -DRS_DECLARE_EXPIRED_APIS -Xclang -target-feature -Xclang +long64  frameworks/rs/driver/runtime/arch/generic.c -o out/target/product/generic/obj/SHARED_LIBRARIES/libclcore.bc_intermediates/arch/generic.bc) && (cp out/target/product/generic/obj/SHARED_LIBRARIES/libclcore.bc_intermediates/arch/generic.d out/target/product/generic/obj/SHARED_LIBRARIES/libclcore.bc_intermediates/arch/generic.P; sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' -e '/^$$/ d' -e 's/$$/ :/' < out/target/product/generic/obj/SHARED_LIBRARIES/libclcore.bc_intermediates/arch/generic.d >> out/target/product/generic/obj/SHARED_LIBRARIES/libclcore.bc_intermediates/arch/generic.P; rm -f out/target/product/generic/obj/SHARED_LIBRARIES/libclcore.bc_intermediates/arch/generic.d)"
            )?,
            (
                Some("out/target/product/generic/obj/SHARED_LIBRARIES/libclcore.bc_intermediates/arch/generic.d".into()),
                "(echo \"bc: libclcore.bc <= frameworks/rs/driver/runtime/arch/generic.c\") && (mkdir -p out/target/product/generic/obj/SHARED_LIBRARIES/libclcore.bc_intermediates/arch/) && (prebuilts/clang/linux-x86/host/3.6/bin/clang -Iframeworks/rs/scriptc -Iexternal/clang/lib/Headers -MD -DRS_VERSION=23 -std=c99 -c -O3 -fno-builtin -emit-llvm -target armv7-none-linux-gnueabi -fsigned-char   -Iframeworks/rs/cpu_ref -DRS_DECLARE_EXPIRED_APIS -Xclang -target-feature -Xclang +long64  frameworks/rs/driver/runtime/arch/generic.c -o out/target/product/generic/obj/SHARED_LIBRARIES/libclcore.bc_intermediates/arch/generic.bc) && (cp out/target/product/generic/obj/SHARED_LIBRARIES/libclcore.bc_intermediates/arch/generic.d out/target/product/generic/obj/SHARED_LIBRARIES/libclcore.bc_intermediates/arch/generic.P; sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' -e '/^$$/ d' -e 's/$$/ :/' < out/target/product/generic/obj/SHARED_LIBRARIES/libclcore.bc_intermediates/arch/generic.d >> out/target/product/generic/obj/SHARED_LIBRARIES/libclcore.bc_intermediates/arch/generic.P)".into()
            )
        );
        assert_eq!(get_depfile("gcc -c foo.P.c")?, None);
        assert_eq!(get_depfile("gcc -MMD foo.o -o foo")?, None);
        // TODO: Fix for automake.
        // assert_eq!(get_depfile("(/bin/sh ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I./src -I./src     -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare  -DNO_FRAME_POINTER  -DNDEBUG -g -O2 -MT libglog_la-logging.lo -MD -MP -MF .deps/libglog_la-logging.Tpo -c -o libglog_la-logging.lo `test -f 'src/logging.cc' || echo './'`src/logging.cc) && (mv -f .deps/libglog_la-logging.Tpo .deps/libglog_la-logging.Plo)")?, Some(".deps/libglog_la-logging.Plo".into()));
        // assert_eq!(get_depfile("(g++ -DHAVE_CONFIG_H -I. -I./src  -I./src  -pthread     -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare  -DNO_FRAME_POINTER  -g -O2 -MT signalhandler_unittest-signalhandler_unittest.o -MD -MP -MF .deps/signalhandler_unittest-signalhandler_unittest.Tpo -c -o signalhandler_unittest-signalhandler_unittest.o `test -f 'src/signalhandler_unittest.cc' || echo './'`src/signalhandler_unittest.cc) && (mv -f .deps/signalhandler_unittest-signalhandler_unittest.Tpo .deps/signalhandler_unittest-signalhandler_unittest.Po)")?, Some(".deps/signalhandler_unittest-signalhandler_unittest.Po".into()));
        Ok(())
    }
}
